### ISSUE TITLE
export file to large, load error

### ISSUE THREAD

**Issue by junpengli** [p/redis-dump-load#27]
json file is 3GB,  load error,   print 'Killed'

**Comment by p** [comment]
A streaming json parser would be necessary to fix that.

**Comment by p** [comment]
@junpengli I added streaming loading support to master, please give it a try.

**Comment by mattcg** [comment]
@p I've tested the latest version and the change doesn't seem to have made any improvement. Entire hashes and lists are still being loaded into memory even when ijson is installed and `redisdl.have_streaming_load` is `True`. A list with 1 million items is currently using > 2GB of RAM for me.
