### ISSUE TITLE
Pickled values

### ISSUE THREAD

**Issue by polcar** [p/redis-dump-load#37]
I am storing pickled python object as Redis values.
I would like to specify function that convert (depickle/jsonifu) redis values. Is it possible?

**Comment by p** [comment]
redis-dump-load should be able to dump these values like any other string values. There is no need to depickle them.

**Comment by polcar** [comment]
I see but I what I want is to dump a human-readable data.

**Comment by p** [comment]
You could do this fairly straightforwardly by overwriting `_reader` and `_writer` methods with ones that unpickle and pickle the values, respectively, and delegate to the base methods for the actual reading and writing.
