### ISSUE TITLE
Unknown distribution option: 'entry_points'   warnings.warn(msg) when install

### ISSUE THREAD

**Issue by koujun2012** [p/redis-dump-load#55]
/usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
/usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)

**Comment by p** [comment]
These are used by pip.
